language: python
python: 3.6-dev
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - python -m pytest --cov=app/tests/v2
after_success:
- coveralls
